name: CD - Deploy no GitHub Pages - v3

on:
  workflow_run:
    workflows: ["CI - Validacao Estrutural HTML"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  actions: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Só executa se o CI tiver sido concluído com sucesso
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Baixar artefato gerado pelo CI
        uses: actions/download-artifact@v4

      - name: Configuração do GitHub Pages
        uses: actions/configure-pages@v4

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /
