name: CD - Deploy no GitHub Pages

on:
  workflow_run:
    workflows: ["CI - Validacao Estrutural HTML"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  actions: read        # IMPORTANTE → permite baixar artefatos de outros workflows
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Baixar artefato do CI
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: site/
          run-id: ${{ github.event.workflow_run.id }}   # <- ESSENCIAL
          repository: ${{ github.event.workflow_run.repository.full_name }}

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
