name: CD - Deploy no GitHub Pages - v3

on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: ["CI - Integracao Continua"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  actions: read
  id-token: write

jobs:
  deploy:
    name: Publicar no GitHub Pages
    runs-on: ubuntu-latest

    # Só executa se o CI tiver sido concluído com sucesso
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout de artefato gerado pelo CI
        uses: actions/checkout@v4

      - name: Configuração do GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload para deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

      - name: Deploy para GitHub Pages
        uses: actions/deploy-pages@v4
