name: CI - Validacao e Testes

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validar-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar htmlhint (validador de HTML)
        run: |
          npm install -g htmlhint

      - name: Validar se o arquivo HTML existe
        run: |
          if [ ! -f "site/index.html" ]; then
            echo "ERRO: site/index.html não encontrado!"
            exit 1
          fi
          echo "Arquivo encontrado!"

      #- name: Validação estrutural do HTML
      #  run: |
      #    echo "Validando estrutura do site/index.html..."
      #    htmlhint site/index.html
      # htmlhint retorna código diferente de 0 se encontrar erro

      - name: Criar artefato do site
        run: |
          rm -rf dist
          mkdir -p dist
          cp -R site/* dist/
          
      - name: Gerar artefato do site
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: site/
