name: CI - Integracao Continua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validar-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Validar estrutura do site
        run: |
          echo "Verificando se o arquivo index.html existe..."
          if [ ! -f "./site/index.html" ]; then
            echo "ERRO: site/index.html não encontrado!"
            exit 1
          fi
          echo "Arquivo encontrado com sucesso!"
          
      - name: Instalar htmlhint
        run: npm install -g htmlhint

      - name: Validar estrutura HTML
        run: htmlhint site/index.html

      - name: Gerar artefato do site
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: site/
